name: Deploy Next.js to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar a chave SSH manualmente
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

      # Enviar os arquivos para o servidor
      - name: Upload files to cPanel
        run: |
          rsync -avz --exclude=".next" --exclude="node_modules" ./ ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:/home1/${{ secrets.CPANEL_USER }}/homolog.protmundi.com.br/

      # Executar os comandos de build no servidor remoto
      - name: Build and start the app on cPanel
        run: |
          ssh ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          cd /home1/${{ secrets.CPANEL_USER }}/homolog.protmundi.com.br/
          yarn
          yarn build
          pm2 restart protmundi-client || pm2 start npm --name "protmundi-client" -- start
          EOF
